### PR TITLE
26 pf2bodyfile creation time is not available

### PR DESCRIPTION
**Pull request by janstarke**

### CODE REVIEW

**Comment by M1ra1B0T** [comment]
The latest version of [frnsc-prefetch](https://github.com/ForensicRS/frnsc-prefetch) currently is 0.9.1, but 0.11 is required.

**Review by M1ra1B0T — COMMENTED** [review]
This does not seem to fix the initial error. I still get the error "Error: IO operations error: creation time is not available for the filesystem". My setup:
- kali linux vm
- I have connected an external drive with NTFS filesystem.
- An E01 image is stored on the external drive
- I have mounted the E01 image, the mountpath is also on the external drive
- I try to run pf2bodyfile from kali onto the mounted path on the external drive

**Comment by janstarke** [comment]
@M1ra1B0T : can you please give it a try again?

**Review by M1ra1B0T — APPROVED** [review]
I tried again with the new changes and did not ran into an error anymore.

**Pull request merged**
